name: vulnbox-vms

services:
  vulnbox-team01:
    build:
      context: .
      dockerfile: vm-dind/Dockerfile
    image: vulnbox-dind:local
    container_name: vulnbox-team01
    hostname: vm-team01
    privileged: true
    restart: unless-stopped
    environment:
      TEAM_ID: "1"
      DOCKER_TLS_CERTDIR: ""
      SSH_ROOT_PASSWORD: "66ec06ebf2ed16a02aceb9c59af4de4d6bf28cbe"
    volumes:
      - dind-data-team01:/var/lib/docker
    networks:
      vulnbox_vm_net:
        ipv4_address: 10.60.1.1
  vulnbox-team02:
    build:
      context: .
      dockerfile: vm-dind/Dockerfile
    image: vulnbox-dind:local
    container_name: vulnbox-team02
    hostname: vm-team02
    privileged: true
    restart: unless-stopped
    environment:
      TEAM_ID: "2"
      DOCKER_TLS_CERTDIR: ""
      SSH_ROOT_PASSWORD: "bcd1eadbd9538736dcce14efd6ffe2decf813cc1"
    volumes:
      - dind-data-team02:/var/lib/docker
    networks:
      vulnbox_vm_net:
        ipv4_address: 10.60.2.1
  vulnbox-team03:
    build:
      context: .
      dockerfile: vm-dind/Dockerfile
    image: vulnbox-dind:local
    container_name: vulnbox-team03
    hostname: vm-team03
    privileged: true
    restart: unless-stopped
    environment:
      TEAM_ID: "3"
      DOCKER_TLS_CERTDIR: ""
      SSH_ROOT_PASSWORD: "d470f6ebffcccead8d2edf6bf05dd16bd89da7fe"
    volumes:
      - dind-data-team03:/var/lib/docker
    networks:
      vulnbox_vm_net:
        ipv4_address: 10.60.3.1
  vulnbox-team04:
    build:
      context: .
      dockerfile: vm-dind/Dockerfile
    image: vulnbox-dind:local
    container_name: vulnbox-team04
    hostname: vm-team04
    privileged: true
    restart: unless-stopped
    environment:
      TEAM_ID: "4"
      DOCKER_TLS_CERTDIR: ""
      SSH_ROOT_PASSWORD: "eadb9b4366cb0df94c720d5bcdba8cebdb475cdf"
    volumes:
      - dind-data-team04:/var/lib/docker
    networks:
      vulnbox_vm_net:
        ipv4_address: 10.60.4.1
  vulnbox-team05:
    build:
      context: .
      dockerfile: vm-dind/Dockerfile
    image: vulnbox-dind:local
    container_name: vulnbox-team05
    hostname: vm-team05
    privileged: true
    restart: unless-stopped
    environment:
      TEAM_ID: "5"
      DOCKER_TLS_CERTDIR: ""
      SSH_ROOT_PASSWORD: "60d47d0646ace8adefb4b5dc67a3a0bffaeabdbe"
    volumes:
      - dind-data-team05:/var/lib/docker
    networks:
      vulnbox_vm_net:
        ipv4_address: 10.60.5.1
  vulnbox-team06:
    build:
      context: .
      dockerfile: vm-dind/Dockerfile
    image: vulnbox-dind:local
    container_name: vulnbox-team06
    hostname: vm-team06
    privileged: true
    restart: unless-stopped
    environment:
      TEAM_ID: "6"
      DOCKER_TLS_CERTDIR: ""
      SSH_ROOT_PASSWORD: "8f7d079188b2d63e4cdac981537d650af71d590f"
    volumes:
      - dind-data-team06:/var/lib/docker
    networks:
      vulnbox_vm_net:
        ipv4_address: 10.60.6.1
  vulnbox-team07:
    build:
      context: .
      dockerfile: vm-dind/Dockerfile
    image: vulnbox-dind:local
    container_name: vulnbox-team07
    hostname: vm-team07
    privileged: true
    restart: unless-stopped
    environment:
      TEAM_ID: "7"
      DOCKER_TLS_CERTDIR: ""
      SSH_ROOT_PASSWORD: "af7cf39cfdf4cf24dfaccbfc28653cbea5db6c19"
    volumes:
      - dind-data-team07:/var/lib/docker
    networks:
      vulnbox_vm_net:
        ipv4_address: 10.60.7.1

volumes:
  dind-data-team01:
  dind-data-team02:
  dind-data-team03:
  dind-data-team04:
  dind-data-team05:
  dind-data-team06:
  dind-data-team07:

networks:
  vulnbox_vm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.60.0.0/16
