version: "2.2"
# ipv6 is not supported in version 3

services:
  cake_backend_deps:
    scale: 0
    image: cake_backend_deps
    build:
      context: ./cake_backend
      dockerfile: Dockerfile.deps

  cake_cleanup_deps:
    scale: 0
    image: cake_cleanup_deps
    build:
      context: ./cleanup
      dockerfile: Dockerfile.deps

  cake_db:
    image: postgres:17-alpine
    container_name: cake_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cake_user
      POSTGRES_PASSWORD: ilovecake
      POSTGRES_DB: app
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  cake_cleanup:
    image: cake_cleanup
    build:
      context: ./cleanup
      dockerfile: Dockerfile
    container_name: cake_cleanup
    restart: unless-stopped
    depends_on:
      - cake_db
    environment:
      PGHOST: cake_db
      PGDATABASE: app
      PGUSER: maintenance_user
      PGPASSWORD: maintenance_password

  cake_backend:
    image: cake_backend
    build:
      context: ./cake_backend
      dockerfile: Dockerfile
    container_name: cake_backend
    restart: unless-stopped
    ports:
      - "4321:4321"
    depends_on:
      - cake_db
volumes:
  postgres_data:

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd42:d0ce:42::/64"
